# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceModel', models.CharField(max_length=200)),
                ('connection_time', models.DateTimeField()),
                ('lastActiveTime', models.DateTimeField()),
                ('totalDataSetsGiven', models.IntegerField()),
                ('AvgTrainingTime', models.FloatField()),
                ('AvgValTime', models.FloatField()),
                ('minibatchID', models.IntegerField()),
                ('epoch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('epochID', models.IntegerField(primary_key=True, serialize=False)),
                ('startingTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('hitRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniBatch',
            fields=[
                ('minibatchID', models.IntegerField(primary_key=True, serialize=False)),
                ('imageIndices', models.IntegerField()),
                ('epochNumber', models.IntegerField()),
                ('deviceID', models.IntegerField()),
                ('status', models.IntegerField()),
                ('startComputingTime', models.DateTimeField()),
                ('isTrain', models.BooleanField(default=True)),
                ('deviceIDSQL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MNISTDist.Device')),
            ],
        ),
    ]
