# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('devicemodel', models.CharField(max_length=200)),
                ('connection_time', models.DateTimeField()),
                ('lastActiveTime', models.DateTimeField()),
                ('totaldatasetsgiven', models.IntegerField()),
                ('AvgTrainingTime', models.FloatField()),
                ('AvgValTime', models.FloatField()),
                ('minibatchID', models.IntegerField()),
                ('epoch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniBatch',
            fields=[
                ('minibatchID', models.IntegerField(primary_key=True, serialize=False)),
                ('imageIndices', models.IntegerField()),
                ('epochNumber', models.IntegerField()),
                ('deviceID', models.IntegerField()),
                ('status', models.IntegerField()),
                ('startComputingTime', models.DateTimeField()),
                ('deviceIDSQL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MNISTDist.Device')),
            ],
        ),
    ]
