# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNISTDist', '0002_remove_minibatch_istrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='minibatch',
            name='barT',
            field=models.BooleanField(default=True),
        ),
    ]
