# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNISTDist', '0003_minibatch_bart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minibatch',
            old_name='barT',
            new_name='isTrain',
        ),
    ]
